<?php
if (false){
// Please do not edit this file.
// It is so painful to do.
// This was generated using PUG.
// Use the HTML to Pug converter to convert it to pug, then edit it. 
// Ask lozinski@PythonLinks.info how to do it if you have questions. 
}
?>

<img src="https://greenmaps.us/root/usa/california/Logo/200W" style="padding:20px; float:left;">
  <div style="text-align: right; padding:20px;"><a href="http://cagreens.org/calendar-0">Calendar</a>&nbsp;&nbsp;<a href="https://cagreens.org/contact-us">Contact Us</a></div>
  <nav class="navbar navbar-expand-lg navbar-light bg-light"><a class="navbar-brand" href="#"></a><button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item dropdown"><a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">NEWS</a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown"><a class="dropdown-item" href="https://cagreens.org/press-releases">PRESS RELEASES</a><a class="dropdown-item" href="https://cagreens.org/press-releases">ANNOUNCEMENTS</a>
            <div class="dropdown-divider"></div>
          </div>
        </li>
        <li class="nav-item dropdown"><a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">ELECTIONS</a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown"><a class="dropdown-item" href="https://www.cagreens.org/green-party-california-state-voter-guide-nov-2024" title="2024 Voter Guide">2024 Voter Guide</a></div>
        </li>
        <li class="nav-item dropdown"><a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">PARTICIPATE</a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown"><a class="dropdown-item" href="/register-green-party" title="Why Register Green Party">Register Green</a><a class="dropdown-item" href="/county-party-directory" title="Green Party county organizations">County Parties</a><a class="dropdown-item" href="/committees" title="">Committees</a><a class="dropdown-item" href="/delegation" title="GPCA Delegation to the Green National Committee of the Green Party of the United States">GPUS Delegation</a><a class="dropdown-item" href="http://www.cagreens.org/elections/run-green" title="Run for office as a Green">Run Green</a><a class="dropdown-item" href="http://www.cagreens.org/action/stop-top-two" title="Overturn the Top Two Primary in California">Stop Top Two</a><a class="dropdown-item" href="http://cagreens.nationbuilder.com/media_resources" title="">Media Resources</a>
            <div class="dropdown-divider"></div>
          </div>
        </li>
        <li class="nav-item dropdown"><a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">PARTY</a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown"><a class="dropdown-item" href="/structure" title="Structure of the Green Party of California">Structure</a><a class="dropdown-item" href="/ga" title="General Assemblies are the state business meetings of the Green Party of California">General Assembly</a><a class="dropdown-item" href="/officers" title="Officials and officials of the Green Party of California">Officers</a><a class="dropdown-item" href="/bylaws-rules-procedures" title="">Bylaws, Rules &amp; Procedures</a><a class="dropdown-item" href="/county-councils" title="County Councils are the legal body of the GPCA on the county level ">County Councils</a><a class="dropdown-item" href="/history" title="">History</a><a class="dropdown-item" href="https://www.gp.org/" title="">Green Party of the US</a>
            <div class="dropdown-divider"></div>
          </div>
        </li>
        <li class="nav-item dropdown"><a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">PLATFORM</a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown"><a class="dropdown-item" href="/ten-key-values" title="Ten Key Values of the Green Party of California">Ten Key Values</a><a class="dropdown-item" href="/platform/economics" title="">Community-Based Sustainable Economics</a><a class="dropdown-item" href="/platform/democracy" title="">Democracy and Electoral Reform</a><a class="dropdown-item" href="/platform/ecology" title="">Ecology</a><a class="dropdown-item" href="/platform/peace-non-violence" title="">Peace and Non-violence</a><a class="dropdown-item" href="/platform/social-justice" title="">Social Justice and Livable Communities</a>
            <div class="dropdown-divider"></div>
          </div>
        </li>
      </ul>
    </div>
  </nav>
